stages:
  - publish
  - deploy
variables:
  TAG_OLD: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:old
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_BVV: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:bvv
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA  
publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_BVV -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push 
    - docker push $TAG_LATEST
  only:
    - master
deploy:
  image: ubuntu:18.04
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apt update && apt install -y openssh-client 
    - scp -i $ID_RSA -o StrictHostKeyChecking=no $MINIKUBE_ENVIR $SERVER_USER@$SERVER_IP:~/.ssh/environment   
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo systemctl restart sshd"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker tag $TAG_BVV $TAG_OLD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker image rm -f $TAG_BVV || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker tag $TAG_LATEST $TAG_BVV"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker image rm -f $TAG_LATEST || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "kubectl delete deployment $MY_PROJECT || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "kubectl delete service $MY_PROJECT || true"
    # - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker image ls"    
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $MY_PROJECT || true"    
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "kubectl create deployment $MY_PROJECT --image=$TAG_BVV"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "kubectl expose deployment $MY_PROJECT --name=$MY_PROJECT --port=8006 --type=LoadBalancer" 
    - sleep 30
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "rm -rf ~/.ssh/environment" 
  
  environment:
    name: production
    url: http://$SERVER_IP
  only:
    - master
